import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Add request validation
function validateRequest(request) {
  return true;
}

const apiKey = process.env.GOOGLE_GEMINI_API_KEY || process.env.GEMINI_API_KEY;
const genAI = apiKey ? new GoogleGenerativeAI(apiKey) : null;

// Dynamic algorithmic fallback questions just in case the API key is missing or generation fails
function generateDynamicAssessmentQuestions(moduleName, count = 10) {
  const templates = {
    AptitudeModule: [
      { template: "If you have {a} items and lose {b}, how many remain?", type: "math" },
      { template: "What is the product of {a} and {c}?", type: "math" },
      { template: "If an object travels {c} km in {a} hours, what is its speed?", type: "math" }
    ],
    GeneralLifeUnderstanding: [
      { template: "How do you usually handle {context}?", type: "behavioral" },
      { template: "In a situation involving {context}, what is your primary focus?", type: "behavioral" }
    ],
    WorkStyleProfiler: [
      { template: "When working in {context}, do you prefer to work alone or in a team?", type: "preference" },
      { template: "How do you react to {context}?", type: "preference" }
    ],
    TechInterestExplorer: [
      { template: "Which area of {context} interests you the most?", type: "preference" },
      { template: "Would you rather work on {context} or {context2}?", type: "preference" }
    ]
  };

  const contexts = {
    GeneralLifeUnderstanding: ["time management", "stressful scenarios", "team conflicts", "personal growth"],
    WorkStyleProfiler: ["a fast-paced project", "a highly regulated environment", "an ambiguous task", "a collaborative meeting"],
    TechInterestExplorer: ["front-end development", "back-end architecture", "artificial intelligence", "data science"],
    AptitudeModule: [] 
  };

  const moduleTemplates = templates[moduleName] || templates.AptitudeModule;
  const moduleContexts = contexts[moduleName] || ["general context"];
  
  const questions = [];
  for (let i = 0; i < count; i++) {
    const templateObj = moduleTemplates[Math.floor(Math.random() * moduleTemplates.length)];
    let questionText = templateObj.template;
    let correctIdx = templateObj.type === 'preference' ? -1 : Math.floor(Math.random() * 4);
    
    if (templateObj.type === "math") {
      const a = Math.floor(Math.random() * 20) + 1;
      const b = Math.floor(Math.random() * 10) + 1;
      const c = Math.floor(Math.random() * 50) + 10;
      questionText = questionText.replace("{a}", a).replace("{b}", b).replace("{c}", c);
    } else {
      const ctx1 = moduleContexts[Math.floor(Math.random() * moduleContexts.length)];
      const ctx2 = moduleContexts[Math.floor(Math.random() * moduleContexts.length)];
      questionText = questionText.replace("{context}", ctx1).replace("{context2}", ctx2);
    }

    questions.push({
      id: 100 + i,
      question: questionText,
      options: ["Autogenerated A", "Autogenerated B", "Autogenerated C", "Autogenerated D"], 
      correct: correctIdx,
      category: moduleName,
      difficulty: "basic",
      explanation: "Auto-generated via algorithmic fallback."
    });
  }
  return questions;
}

export async function GET(request) {
  try {
    if (!validateRequest(request)) {
      return NextResponse.json({ success: false, error: 'Invalid request' }, { status: 400 });
    }

    const { searchParams } = new URL(request.url);
    const module = searchParams.get('module') || 'AptitudeModule';

    if (!genAI) {
      console.warn("No Gemini API Key provided. Returning fallback question.");
      return NextResponse.json({
        success: true,
        module: module,
        questions: generateDynamicAssessmentQuestions(module)
      });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    
    // Create an explicit prompt for exactly the category requested
    const prompt = `You are an expert career assessment developer. Generate exactly 10 engaging, beginner-to-intermediate multiple-choice questions for an assessment module titled "${module}".
    
The module should evaluate the user's foundation, logic, or preferences according to the module name.
1. "AptitudeModule" -> math, logic, reasoning.
2. "GeneralLifeUnderstanding" -> social intelligence, time management, empathy.
3. "WorkStyleProfiler" -> collaboration, pressure management, work environment (Note: for preference/profiler questions that have no wrong answer, set 'correct' to -1).
4. "TechInterestExplorer" -> technology interests, AI, software development (Note: set 'correct' to -1 for preference/interest questions).

IMPORTANT REQUIREMENT: Your output MUST be ONLY valid JSON. No markdown backticks or explanations outside the JSON formatting. The JSON must have the following structure:
[
  {
    "id": 1,
    "question": "Question text here?",
    "options": ["Option 1", "Option 2", "Option 3", "Option 4"],
    "correct": 1, 
    "category": "category_name",
    "difficulty": "basic",
    "explanation": "Brief explanation of the answer/concept"
  }
]

Make sure "correct" is an integer index (0-3) indicating the correct option. If the question is purely preference-based (like interest mapping), set "correct": -1.
Return exactly an array of 10 objects. Do not wrap it in any other object. Just the JSON array.`;

    const result = await model.generateContent(prompt);
    let outputText = result.response.text();
    
    // Clean up markdown markers if the model ignored instructions
    outputText = outputText.replace(/```json/g, '').replace(/```/g, '').trim();
    
    let generatedQuestions;
    try {
      generatedQuestions = JSON.parse(outputText);
    } catch (parseErr) {
      console.error("Failed to parse Gemini output:", outputText);
      throw new Error("Invalid format from AI");
    }

    // Assign unique IDs to prevent frontend react key warnings
    generatedQuestions = generatedQuestions.map((q, idx) => ({ ...q, id: idx + 100 }));

    return NextResponse.json({
      success: true,
      module: module,
      questions: generatedQuestions
    });

  } catch (error) {
    console.error('Assessment API error:', error);
    const params = new URL(request.url).searchParams;
    const module = params.get('module') || 'AptitudeModule';
    return NextResponse.json({
      success: true,
      module: module,
      questions: generateDynamicAssessmentQuestions(module)
    });
  }
}